# Generated by Django 5.0.6 on 2024-05-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentModel",
            fields=[
                (
                    "controlutility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utilities.controlutility",
                    ),
                ),
                (
                    "incidentId",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="incident id"
                    ),
                ),
                ("details", models.TextField(verbose_name="incident details")),
                (
                    "incidentType",
                    models.CharField(
                        choices=[
                            ("enterprise", "enterprise"),
                            ("goverment", "goverment"),
                        ],
                        default="enterprise",
                        max_length=50,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        default="low",
                        max_length=50,
                        verbose_name="Incident Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("in_process", "in_process"),
                            ("low", "low"),
                        ],
                        default="open",
                        max_length=50,
                        verbose_name="Incident Status",
                    ),
                ),
                (
                    "createBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportedBy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Incident reporter",
                    ),
                ),
            ],
            options={
                "verbose_name": "IncidentModel",
                "verbose_name_plural": "IncidentModels",
            },
            bases=("utilities.controlutility",),
        ),
    ]
