# Generated by Django 5.0.6 on 2024-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidentModule", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IncidentModel",
        ),
    ]
