# Generated by Django 5.0.6 on 2024-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControlUtility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ControlUtility",
                "verbose_name_plural": "ControlUtilities",
            },
        ),
    ]
